services:
  nginx:
    build:
      context: ./docker/nginx
    ports:
      - "8080:80"
    volumes:
      - .:/app
    networks:
      - app-network
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: ./docker
      dockerfile: php-fpm/Dockerfile
    volumes:
      - .:/app
    networks:
      - app-network

  php-cli:
    build:
      context: ./docker
      dockerfile: php-cli/Dockerfile
    tty: true
    stdin_open: true
    volumes:
      - .:/app
    networks:
      - app-network

  postgres:
    image: postgres:17.0-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

volumes:
  postgres:

networks:
  app-network:
    driver: bridge